name = "MudFaceBot"
main = "src/worker.js"
compatibility_date = "2023-12-19"
workers_dev = true

[vars]
PPX_KEY = "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"
TELEGRAM_KEY = "6904631791:AAEXJJHZB-lwB-XstNv7dkyDJYpz0eEL9-M"
ADMIN = "@M.HagenBot"
ADMIN_CHAT_ID = 123456
